name: unique_school_app
description: Unique School System Flutter app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Animations & 3D
  lottie: ^2.7.0
  rive: ^0.12.4
  flutter_cube: ^0.1.1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # UI & Icons
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  
  # Advanced UI Components
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.0.0
  pull_to_refresh: ^2.0.0
  glass_kit: ^3.0.0
  
  # Utils
  url_launcher: ^6.2.2
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/animations/
    - assets/3d/
