name: Build Android APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: unique_school_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate platforms if missing
        run: |
          if [ ! -d "android" ]; then flutter create .; fi

      - name: Build release APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: unique-school-apk
          path: unique_school_app/build/app/outputs/flutter-apk/app-release.apk
